

alter session set STATISTICS_LEVEL=all;

ALTER SESSION ENABLE PARALLEL DML;

ALTER SESSION FORCE PARALLEL DML PARALLEL 8;

set timing on

truncate table Oprdta.F0911_C08_2 reuse storage;


Insert /*+parallel(8)*/ Into Oprdta.F0911_C08_2
(
GLBCRC,                         
GLCRRM,                         
GLTXA1,                         
GLEXR1,                         
GLKCO,                          
GLDCT,                          
GLDOC,                          
GLDGJ,                          
GLJELN,                         
GLEXTL,                         
GLPOST,                         
GLICU,                          
GLICUT,                         
GLDICJ,                         
GLDSYJ,                         
GLTICU,                         
GLCO,                           
GLANI,                          
GLAM,                           
GLAID,                          
GLMCU,                          
GLOBJ,                          
GLSUB,                          
GLSBL,                          
GLSBLT,                         
GLLT,                           
GLPN,                           
GLCTRY,                         
GLFY,                           
GLCRCD,                         
GLCRR,                          
GLAA,                           
GLU,                            
GLUM,                           
GLGLC,                          
GLRE,                           
GLEXA,                          
GLEXR,                          
GLR1,                           
GLR2,                           
GLR3,                           
GLODOC,                         
GLODCT,                         
GLPKCO,                         
GLOKCO,                         
GLPDCT,                         
GLAN8,                          
GLCN,                           
GLASID,                         
GLBRE,                          
GLRCND,                         
GLPRGE,                         
GLVINV,                         
GLIVD,                          
GLPO,                           
GLPSFX,                         
GLDCTO,                         
GLLNID,                         
GLDSVJ,                         
GLTORG,                         
GLUSER,                         
GLPID,                          
GLJOBN,                         
GLUPMJ,                         
GLUPMT,                         
GLABR1,                         
GLABR2,                         
GLABR3,                         
GLABR4,                         
GLABT1,                         
GLABT2,                         
GLABT3,                         
Glabt4,                         
Glitm,
GLDGJ_DATE,                     
GLDICJ_DATE,                    
Gldsyj_Date,                    
Glhdgj_Date,                    
Gldkj_Date,                     
GLDKC_DATE,                     
GLIVD_DATE,                     
GLDSVJ_DATE,                    
GLUPMJ_DATE,                    
GLABR1_NVC,                     
GLABR2_NVC,                     
GLABR3_NVC,                     
GLABR4_NVC,                     
GLANI_NVC,                      
GLMCU_NVC,                      
GLOBJ_NVC,                      
GLSUB_NVC,                      
GLSBL_NVC,                      
Glcn_Nvc,                       
Glvinv_Nvc
)
Select /*+parallel(8)*/ 
GLBCRC,                         
GLCRRM,                         
GLTXA1,                         
GLEXR1,                         
GLKCO,                          
GLDCT,                          
GLDOC,                          
GLDGJ,                          
GLJELN,                         
GLEXTL,                         
GLPOST,                         
GLICU,                          
GLICUT,                         
GLDICJ,                         
GLDSYJ,                         
GLTICU,                         
GLCO,                           
GLANI,                          
GLAM,                           
GLAID,                          
GLMCU,                          
GLOBJ,                          
GLSUB,                          
GLSBL,                          
GLSBLT,                         
GLLT,                           
GLPN,                           
GLCTRY,                         
GLFY,                           
GLCRCD,                         
GLCRR,                          
GLAA,                           
GLU,                            
GLUM,                           
GLGLC,                          
GLRE,                           
GLEXA,                          
GLEXR,                          
GLR1,                           
GLR2,                           
GLR3,                           
GLODOC,                         
GLODCT,                         
GLPKCO,                         
GLOKCO,                         
GLPDCT,                         
GLAN8,                          
GLCN,                           
GLASID,                         
GLBRE,                          
GLRCND,                         
GLPRGE,                         
GLVINV,                         
GLIVD,                          
GLPO,                           
GLPSFX,                         
GLDCTO,                         
GLLNID,                         
GLDSVJ,                         
GLTORG,                         
GLUSER,                         
GLPID,                          
GLJOBN,                         
GLUPMJ,                         
GLUPMT,                         
GLABR1,                         
GLABR2,                         
GLABR3,                         
GLABR4,                         
GLABT1,                         
GLABT2,                         
GLABT3,                         
Glabt4,                         
Glitm,
To_Date(Gldgj+'1900000','YYYYDDD') "GLDGJ_DATE",                     
To_Date(Gldicj+'1900000','YYYYDDD') "GLDICJ_DATE",                    
To_Date(Gldsyj+'1900000','YYYYDDD') "Gldsyj_Date",  
Decode(Glhdgj,0,Null,To_Date(Glhdgj+'1900000','YYYYDDD')) "GLHDGJ_DATE", 
Decode(Gldkj,0,Null,To_Date(Gldkj+'1900000','YYYYDDD')) "GLDKJ_DATE",
Decode(Gldkc,0,Null,To_Date(Gldkc+'1900000','YYYYDDD')) "GLDKc_DATE",
Decode(Glivd,0,Null,To_Date(Glivd+'1900000','YYYYDDD')) "GLIVD_DATE",
Decode(Gldsvj,0,Null,To_Date(Gldsvj+'1900000','YYYYDDD')) "GLDSVJ_DATE",
To_Date(Glupmj+'1900000','YYYYDDD') "GLUPMJ_DATE",
Decode(Instr(Glabt1,'V'),1,(Decode(Instr(Substr(Glabr1,1,3),'  '),0,Substr(Glabr1,1,2),'NA')),'NA') Glabr1_Nvc,
trim(Decode(Instr(Glabt2,'C'),1,(Decode(Instr(Substr(Glabr2,1,3),'  '),0,Substr(Glabr2,1,3),'NA')),'NA')) Glabr2_Nvc,
Trim(Glabr3) Glabr3_Nvc,
Decode(Instr(Glabt4,'G'),1,(Decode(Instr(Substr(Glabr4,1,3),'  '),0,Substr(Glabr4,1,2),'NA')),'NA') Glabr4_Nvc,
Trim(Glani) Glani_Nvc,
Trim(Glmcu) Glmcu_Nvc,
Trim(Globj) Globj_Nvc,
Trim(Glsub) Glsub_Nvc,
Trim(Glsbl) Glsbl_Nvc,
Trim(Glcn) Glcn_Nvc,
trim(GLVINV) GLVINV_NVC              
From Oprdta.F0911_load
;

commit;

exit; 

